### ISSUE TITLE
Bug in time rounding logic

### ISSUE THREAD

**Issue by mohammad-haque** [alphahm/adhanpy#4]
The calendar util class (CalendarUtil) has a bug which fails in certain value, for example, this fails to round this `dt` because the rounding logic trying to set `minute` to `60` which is invalid.

```
 dt = datetime(2022, 1, 1, 10, 59, 59)
```

**Comment by alphahm** [comment]
In fact, at first look, it appears this would happen whenever minute is 59 and second is > 30, adding 1 minute to 59 (conversely the rounding of unsigned <= 30 / 60 will produce 0). There is certainly a flaw in this regard.

I'll have a think about this... How did you come across this, is this by just reviewing the code? or by testing prayer times at a particular location using a particular calculation method. I'd be interested to know in order to add a few more tests to the library and decide the best course of action.

Thanks.

**Comment by mohammad-haque** [comment]
I was mainly playing with this lib in a side project and one of the prayer time was 59mins and some seconds and that value was causing crash with `datetime.replace`. As you said adding a minute can have cascading effect (to hour, days, month etc) so maybe you can just drop the `seconds` (set to zero)?

On a separate note, do you think this library can have London Unified Time as well?

**Comment by alphahm** [comment]
Yeah, I am starting to question this rounding logic. We might decide to diverge from the original Java implementation on that subject and drop the rounding logic and always set the second to 0. Or second solution, if minute is 59 and second > 30, do not attempt to round, we lose a bit of consistency, but at least we don't break the program.

I am happy to let you create the PR with some tests too if you're confident. Otherwise I'll tackle this at some point.

**Comment by alphahm** [comment]
@mohammad-haque I will be releasing the fix in v1.0.4. Can you create a separate issue for London Unified Time with as much info as possible. Thanks.
